# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20170910_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
