# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=6),
        ),
    ]
