# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20170910_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='lng',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=11),
        ),
    ]
