# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_auto_20171117_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='method',
            field=models.CharField(choices=[('1', 'Delivery'), ('2', 'Pickup'), ('3', 'Delivery & Pickup'), ('4', 'Other Delivery')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
