# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_auto_20171223_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.SlugField(max_length=40),
        ),
    ]
